version: '3.7'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    volumes:
      - ./Kibana/kibana.yml:/usr/share/kibana/config/kibana.yml    
    ports:
      - 5601:5601
    networks:
      - elk
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.6.0
    container_name: metricbeat_docker
    depends_on: [elasticsearch]
    restart: on-failure
    volumes:
      - ./Metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml      
    networks: 
      - elk    
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:6.6.0
    container_name: heartbeat_docker
    depends_on: [elasticsearch]
    restart: on-failure
    volumes: 
      - ./Heartbeat/heartbeat.docker.yml:/heartbeat.yml
    networks: 
      - elk

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
    
networks:
  elk: